name: CI
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v3
    - name: Install ESLint
      run: |
        npm install eslint@^8.42.0
        npm install eslint-config-airbnb-base@^15.0.0
    - name: Run ESLint
      run: npx eslint .

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
